spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_auth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456

  security:
    oauth2:
      jwt:
        signingKey: 123456
  zipkin:
    enabled: true
    baseUrl: http://127.0.0.1:9411
  sleuth:
    sampler:
      rate: 100