spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_org?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456