spring:
  cloud:
    gateway:
      routes:
        - id: echo
          uri: lb://echo
          predicates:
            - Path=/echo/**
        - id: organization
          uri: lb://organization
          order: 1
          predicates:
            - Path=/org/**