spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  cloud:
    stream:
      bindings:
        my_topic_output:
          destination: aaa-topic
          binder: local_rabbit
        my_topic_input:
          destination: aaa-topic
          group: demo_group
          binder: local_rabbit
        my_topic1_input:
          destination: aaa-topic
          group: demo_group1
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBIT_MQ_HOST:localhost}
                port: ${RABBIT_MQ_PORT:5672}
                username: ${RABBIT_MQ_USERNAME:guest}
                password: ${RABBIT_MQ_PASSWORD:guest}
                virtual-host: /
  zipkin:
    enabled: true
    baseUrl: http://127.0.0.1:9411
  sleuth:
    sampler:
      rate: 100

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
